cookietemple_version: '1.3.10 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: augurpy
project_slug_no_hyphen: augurpy
template_version: '2.0.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: theislab
creator_github_username: zethson
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: theislab
full_name: Lukas Heumos
email: lukas.heumos@posteo.net
project_name: augurpy
project_short_description: A Python adaption of Augur to prioritize cell types in
  perturbation analysis.
version: 0.1.0
license: MIT
